import { type Category } from "@shared/schema";

export const categories: Category[] = [
  {
    id: "movies",
    name: "Movies",
    icon: "Film",
    color: "text-primary",
    words: [
      "The Shawshank Redemption",
      "The Godfather",
      "Star Wars",
      "Titanic",
      "Avatar",
      "Jurassic Park",
      "The Lion King",
      "Forrest Gump",
      "Inception",
      "The Matrix",
      "Pulp Fiction",
      "Fight Club",
      "The Dark Knight",
      "Schindler's List",
      "The Wizard of Oz",
      "Casablanca",
      "Gone with the Wind",
      "E.T.",
      "Jaws",
      "Rocky",
      "Toy Story",
      "Finding Nemo",
      "Frozen",
      "The Avengers",
      "Iron Man",
      "Spider-Man",
      "Harry Potter",
      "Lord of the Rings",
      "Pirates of the Caribbean",
      "Back to the Future",
      "Ghostbusters",
      "Indiana Jones",
      "Terminator",
      "Die Hard",
      "Mission Impossible",
      "James Bond",
      "Shrek",
      "The Incredibles",
      "Up",
      "Wall-E",
      "Ratatouille",
      "Monsters Inc",
      "The Jungle Book",
      "Aladdin",
      "Beauty and the Beast",
      "The Little Mermaid",
      "Mulan",
      "Pocahontas",
      "Tarzan",
      "Kung Fu Panda",
      "Madagascar",
      "Ice Age",
      "Rio",
      "Happy Feet",
      "Rango",
      "Moana",
      "Coco",
      "Encanto",
      "Turning Red",
    ],
  },
  {
    id: "animals",
    name: "Animals",
    icon: "Dog",
    color: "text-secondary",
    words: [
      "Elephant",
      "Lion",
      "Tiger",
      "Bear",
      "Wolf",
      "Fox",
      "Deer",
      "Rabbit",
      "Squirrel",
      "Raccoon",
      "Skunk",
      "Beaver",
      "Otter",
      "Seal",
      "Walrus",
      "Penguin",
      "Polar Bear",
      "Giraffe",
      "Zebra",
      "Hippopotamus",
      "Rhinoceros",
      "Crocodile",
      "Alligator",
      "Lizard",
      "Snake",
      "Turtle",
      "Frog",
      "Toad",
      "Salamander",
      "Dolphin",
      "Whale",
      "Shark",
      "Octopus",
      "Jellyfish",
      "Starfish",
      "Crab",
      "Lobster",
      "Shrimp",
      "Eagle",
      "Hawk",
      "Owl",
      "Parrot",
      "Flamingo",
      "Peacock",
      "Ostrich",
      "Kangaroo",
      "Koala",
      "Panda",
      "Gorilla",
      "Chimpanzee",
      "Monkey",
      "Sloth",
      "Armadillo",
      "Anteater",
      "Hedgehog",
      "Porcupine",
      "Bat",
      "Butterfly",
      "Bee",
      "Ladybug",
    ],
  },
  {
    id: "celebrities",
    name: "Celebrities",
    icon: "Star",
    color: "text-accent",
    words: [
      "Leonardo DiCaprio",
      "Tom Hanks",
      "Meryl Streep",
      "Brad Pitt",
      "Angelina Jolie",
      "Johnny Depp",
      "Robert Downey Jr",
      "Scarlett Johansson",
      "Chris Hemsworth",
      "Jennifer Lawrence",
      "Emma Watson",
      "Ryan Reynolds",
      "Dwayne Johnson",
      "Will Smith",
      "Morgan Freeman",
      "Denzel Washington",
      "Sandra Bullock",
      "Julia Roberts",
      "Tom Cruise",
      "Nicole Kidman",
      "George Clooney",
      "Matt Damon",
      "Ben Affleck",
      "Jennifer Aniston",
      "Reese Witherspoon",
      "Cameron Diaz",
      "Jim Carrey",
      "Adam Sandler",
      "Eddie Murphy",
      "Robin Williams",
      "Oprah Winfrey",
      "Ellen DeGeneres",
      "Jimmy Fallon",
      "Stephen Colbert",
      "Taylor Swift",
      "Beyoncé",
      "Rihanna",
      "Lady Gaga",
      "Ariana Grande",
      "Ed Sheeran",
      "Justin Bieber",
      "Selena Gomez",
      "Drake",
      "Kanye West",
      "Jay-Z",
      "Eminem",
      "Snoop Dogg",
      "Michael Jackson",
      "Madonna",
      "Elvis Presley",
      "The Beatles",
      "Rolling Stones",
      "Queen",
      "David Bowie",
      "Prince",
      "Whitney Houston",
      "Mariah Carey",
      "Celine Dion",
      "Adele",
      "Bruno Mars",
    ],
  },
  {
    id: "actions",
    name: "Actions",
    icon: "Sparkles",
    color: "text-chart-4",
    words: [
      "Running",
      "Jumping",
      "Dancing",
      "Swimming",
      "Climbing",
      "Crawling",
      "Walking",
      "Skipping",
      "Hopping",
      "Flying",
      "Diving",
      "Surfing",
      "Skiing",
      "Skating",
      "Biking",
      "Driving",
      "Cooking",
      "Eating",
      "Drinking",
      "Sleeping",
      "Snoring",
      "Yawning",
      "Stretching",
      "Exercising",
      "Yoga",
      "Meditation",
      "Painting",
      "Drawing",
      "Writing",
      "Reading",
      "Singing",
      "Playing Guitar",
      "Playing Piano",
      "Playing Drums",
      "Conducting Orchestra",
      "Acting",
      "Juggling",
      "Magic Tricks",
      "Clapping",
      "Waving",
      "Pointing",
      "Thumbs Up",
      "High Five",
      "Fist Bump",
      "Hugging",
      "Kissing",
      "Laughing",
      "Crying",
      "Screaming",
      "Whispering",
      "Shouting",
      "Sneezing",
      "Coughing",
      "Blowing Nose",
      "Brushing Teeth",
      "Combing Hair",
      "Shaving",
      "Taking Selfie",
      "Texting",
      "Typing",
    ],
  },
  {
    id: "objects",
    name: "Objects",
    icon: "Package",
    color: "text-chart-5",
    words: [
      "Smartphone",
      "Laptop",
      "Television",
      "Remote Control",
      "Headphones",
      "Camera",
      "Microphone",
      "Guitar",
      "Piano",
      "Drums",
      "Trumpet",
      "Violin",
      "Basketball",
      "Football",
      "Soccer Ball",
      "Tennis Racket",
      "Golf Club",
      "Baseball Bat",
      "Bicycle",
      "Skateboard",
      "Scooter",
      "Roller Skates",
      "Snowboard",
      "Skis",
      "Surfboard",
      "Umbrella",
      "Backpack",
      "Suitcase",
      "Wallet",
      "Keys",
      "Watch",
      "Sunglasses",
      "Hat",
      "Shoes",
      "Boots",
      "Gloves",
      "Scarf",
      "Jacket",
      "Book",
      "Notebook",
      "Pen",
      "Pencil",
      "Eraser",
      "Ruler",
      "Scissors",
      "Stapler",
      "Calculator",
      "Coffee Mug",
      "Water Bottle",
      "Plate",
      "Fork",
      "Knife",
      "Spoon",
      "Bowl",
      "Pan",
      "Pot",
      "Toaster",
      "Blender",
      "Microwave",
    ],
  },
  {
    id: "music",
    name: "Music",
    icon: "Music",
    color: "text-chart-1",
    words: [
      "Bohemian Rhapsody",
      "Stairway to Heaven",
      "Imagine",
      "Hey Jude",
      "Like a Rolling Stone",
      "Smells Like Teen Spirit",
      "Purple Haze",
      "Hotel California",
      "Sweet Child O' Mine",
      "Billie Jean",
      "Thriller",
      "Beat It",
      "Wonderwall",
      "Don't Stop Believin'",
      "Livin' on a Prayer",
      "Sweet Home Alabama",
      "Crazy in Love",
      "Single Ladies",
      "Rolling in the Deep",
      "Shape of You",
      "Uptown Funk",
      "Happy",
      "Get Lucky",
      "Blinding Lights",
      "Levitating",
      "drivers license",
      "All the Small Things",
      "Mr. Brightside",
      "Seven Nation Army",
      "Radioactive",
      "Counting Stars",
      "Shake It Off",
      "Blank Space",
      "Bad Guy",
      "Old Town Road",
      "Despacito",
      "Gangnam Style",
      "Call Me Maybe",
      "Somebody That I Used to Know",
      "Royals",
      "Can't Stop the Feeling",
      "Party Rock Anthem",
      "Firework",
      "Roar",
      "Dark Horse",
      "California Gurls",
      "Teenage Dream",
      "We Are Young",
      "Pumped Up Kicks",
      "Some Nights",
      "Wake Me Up",
      "Chandelier",
      "Titanium",
      "Without Me",
      "Sunflower",
      "Perfect",
      "Thinking Out Loud",
      "Photograph",
      "Castle on the Hill",
      "Someone Like You",
    ],
  },
  {
    id: "sports",
    name: "Sports",
    icon: "Trophy",
    color: "text-chart-2",
    words: [
      "Soccer",
      "Basketball",
      "American Football",
      "Baseball",
      "Tennis",
      "Golf",
      "Swimming",
      "Track and Field",
      "Volleyball",
      "Rugby",
      "Cricket",
      "Hockey",
      "Figure Skating",
      "Gymnastics",
      "Boxing",
      "Wrestling",
      "Martial Arts",
      "Skiing",
      "Snowboarding",
      "Surfing",
      "Skateboarding",
      "BMX",
      "Cycling",
      "Marathon",
      "Triathlon",
      "Diving",
      "Water Polo",
      "Lacrosse",
      "Badminton",
      "Table Tennis",
      "Bowling",
      "Archery",
      "Fencing",
      "Karate",
      "Judo",
      "Taekwondo",
      "Rock Climbing",
      "Bungee Jumping",
      "Skydiving",
      "Parkour",
      "Polo",
      "Equestrian",
      "Sailing",
      "Rowing",
      "Kayaking",
      "Rafting",
      "Fishing",
      "Hunting",
      "NASCAR",
      "Formula 1",
      "MotoGP",
      "Drag Racing",
      "Darts",
      "Billiards",
      "Snooker",
      "Chess",
      "Poker",
      "Yoga",
      "Pilates",
      "CrossFit",
    ],
  },
  {
    id: "food",
    name: "Food & Drinks",
    icon: "Apple",
    color: "text-chart-3",
    words: [
      "Pizza",
      "Hamburger",
      "Hot Dog",
      "Tacos",
      "Burrito",
      "Sushi",
      "Ramen",
      "Pasta",
      "Lasagna",
      "Spaghetti",
      "Steak",
      "Fried Chicken",
      "BBQ Ribs",
      "French Fries",
      "Onion Rings",
      "Nachos",
      "Quesadilla",
      "Sandwich",
      "Bagel",
      "Donut",
      "Croissant",
      "Pancakes",
      "Waffles",
      "French Toast",
      "Bacon",
      "Scrambled Eggs",
      "Omelette",
      "Salad",
      "Caesar Salad",
      "Ice Cream",
      "Chocolate Cake",
      "Cheesecake",
      "Brownies",
      "Cookies",
      "Cupcakes",
      "Apple Pie",
      "Pumpkin Pie",
      "Tiramisu",
      "Macarons",
      "Popcorn",
      "Chips",
      "Pretzels",
      "Candy Bar",
      "Lollipop",
      "Gummy Bears",
      "Cotton Candy",
      "Coffee",
      "Espresso",
      "Cappuccino",
      "Latte",
      "Tea",
      "Hot Chocolate",
      "Smoothie",
      "Milkshake",
      "Soda",
      "Lemonade",
      "Orange Juice",
      "Wine",
      "Beer",
      "Cocktail",
    ],
  },
  {
    id: "travel",
    name: "Travel & Places",
    icon: "Plane",
    color: "text-chart-4",
    words: [
      "Eiffel Tower",
      "Statue of Liberty",
      "Big Ben",
      "Taj Mahal",
      "Great Wall of China",
      "Colosseum",
      "Pyramids of Giza",
      "Machu Picchu",
      "Christ the Redeemer",
      "Sydney Opera House",
      "Stonehenge",
      "Burj Khalifa",
      "Golden Gate Bridge",
      "Times Square",
      "Grand Canyon",
      "Niagara Falls",
      "Mount Everest",
      "Sahara Desert",
      "Amazon Rainforest",
      "Great Barrier Reef",
      "Northern Lights",
      "Venice Canals",
      "Santorini",
      "Maldives",
      "Hawaii",
      "Bali",
      "Tokyo",
      "Paris",
      "London",
      "New York City",
      "Los Angeles",
      "San Francisco",
      "Las Vegas",
      "Miami",
      "Rome",
      "Barcelona",
      "Amsterdam",
      "Dubai",
      "Singapore",
      "Hong Kong",
      "Sydney",
      "Melbourne",
      "Rio de Janeiro",
      "Buenos Aires",
      "Mexico City",
      "Cairo",
      "Istanbul",
      "Moscow",
      "Prague",
      "Vienna",
      "Berlin",
      "Stockholm",
      "Copenhagen",
      "Iceland",
      "Norway",
      "Switzerland",
      "Scotland",
      "Ireland",
      "Greece",
      "Thailand",
    ],
  },
];
