import { type Category } from "@shared/schema";

export const categories: Category[] = [
  {
    id: "movies",
    name: "Movies",
    icon: "Film",
    color: "text-primary",
    words: [
      "The Shawshank Redemption",
      "The Godfather",
      "Star Wars",
      "Titanic",
      "Avatar",
      "Jurassic Park",
      "The Lion King",
      "Forrest Gump",
      "Inception",
      "The Matrix",
      "Pulp Fiction",
      "Fight Club",
      "The Dark Knight",
      "Schindler's List",
      "The Wizard of Oz",
      "Casablanca",
      "Gone with the Wind",
      "E.T.",
      "Jaws",
      "Rocky",
      "Toy Story",
      "Finding Nemo",
      "Frozen",
      "The Avengers",
      "Iron Man",
      "Spider-Man",
      "Harry Potter",
      "Lord of the Rings",
      "Pirates of the Caribbean",
      "Back to the Future",
      "Ghostbusters",
      "Indiana Jones",
      "Terminator",
      "Die Hard",
      "Mission Impossible",
      "James Bond",
      "Shrek",
      "The Incredibles",
      "Up",
      "Wall-E",
      "Ratatouille",
      "Monsters Inc",
      "The Jungle Book",
      "Aladdin",
      "Beauty and the Beast",
      "The Little Mermaid",
      "Mulan",
      "Pocahontas",
      "Tarzan",
      "Kung Fu Panda",
      "Madagascar",
      "Ice Age",
      "Rio",
      "Happy Feet",
      "Rango",
      "Moana",
      "Coco",
      "Encanto",
      "Turning Red",
    ],
  },
  {
    id: "animals",
    name: "Animals",
    icon: "Dog",
    color: "text-secondary",
    words: [
      "Elephant",
      "Lion",
      "Tiger",
      "Bear",
      "Wolf",
      "Fox",
      "Deer",
      "Rabbit",
      "Squirrel",
      "Raccoon",
      "Skunk",
      "Beaver",
      "Otter",
      "Seal",
      "Walrus",
      "Penguin",
      "Polar Bear",
      "Giraffe",
      "Zebra",
      "Hippopotamus",
      "Rhinoceros",
      "Crocodile",
      "Alligator",
      "Lizard",
      "Snake",
      "Turtle",
      "Frog",
      "Toad",
      "Salamander",
      "Dolphin",
      "Whale",
      "Shark",
      "Octopus",
      "Jellyfish",
      "Starfish",
      "Crab",
      "Lobster",
      "Shrimp",
      "Eagle",
      "Hawk",
      "Owl",
      "Parrot",
      "Flamingo",
      "Peacock",
      "Ostrich",
      "Kangaroo",
      "Koala",
      "Panda",
      "Gorilla",
      "Chimpanzee",
      "Monkey",
      "Sloth",
      "Armadillo",
      "Anteater",
      "Hedgehog",
      "Porcupine",
      "Bat",
      "Butterfly",
      "Bee",
      "Ladybug",
    ],
  },
  {
    id: "celebrities",
    name: "Celebrities",
    icon: "Star",
    color: "text-accent",
    words: [
      "Leonardo DiCaprio",
      "Tom Hanks",
      "Meryl Streep",
      "Brad Pitt",
      "Angelina Jolie",
      "Johnny Depp",
      "Robert Downey Jr",
      "Scarlett Johansson",
      "Chris Hemsworth",
      "Jennifer Lawrence",
      "Emma Watson",
      "Ryan Reynolds",
      "Dwayne Johnson",
      "Will Smith",
      "Morgan Freeman",
      "Denzel Washington",
      "Sandra Bullock",
      "Julia Roberts",
      "Tom Cruise",
      "Nicole Kidman",
      "George Clooney",
      "Matt Damon",
      "Ben Affleck",
      "Jennifer Aniston",
      "Reese Witherspoon",
      "Cameron Diaz",
      "Jim Carrey",
      "Adam Sandler",
      "Eddie Murphy",
      "Robin Williams",
      "Oprah Winfrey",
      "Ellen DeGeneres",
      "Jimmy Fallon",
      "Stephen Colbert",
      "Taylor Swift",
      "Beyoncé",
      "Rihanna",
      "Lady Gaga",
      "Ariana Grande",
      "Ed Sheeran",
      "Justin Bieber",
      "Selena Gomez",
      "Drake",
      "Kanye West",
      "Jay-Z",
      "Eminem",
      "Snoop Dogg",
      "Michael Jackson",
      "Madonna",
      "Elvis Presley",
      "The Beatles",
      "Rolling Stones",
      "Queen",
      "David Bowie",
      "Prince",
      "Whitney Houston",
      "Mariah Carey",
      "Celine Dion",
      "Adele",
      "Bruno Mars",
    ],
  },
  {
    id: "actions",
    name: "Actions",
    icon: "Sparkles",
    color: "text-chart-4",
    words: [
      "Running",
      "Jumping",
      "Dancing",
      "Swimming",
      "Climbing",
      "Crawling",
      "Walking",
      "Skipping",
      "Hopping",
      "Flying",
      "Diving",
      "Surfing",
      "Skiing",
      "Skating",
      "Biking",
      "Driving",
      "Cooking",
      "Eating",
      "Drinking",
      "Sleeping",
      "Snoring",
      "Yawning",
      "Stretching",
      "Exercising",
      "Yoga",
      "Meditation",
      "Painting",
      "Drawing",
      "Writing",
      "Reading",
      "Singing",
      "Playing Guitar",
      "Playing Piano",
      "Playing Drums",
      "Conducting Orchestra",
      "Acting",
      "Juggling",
      "Magic Tricks",
      "Clapping",
      "Waving",
      "Pointing",
      "Thumbs Up",
      "High Five",
      "Fist Bump",
      "Hugging",
      "Kissing",
      "Laughing",
      "Crying",
      "Screaming",
      "Whispering",
      "Shouting",
      "Sneezing",
      "Coughing",
      "Blowing Nose",
      "Brushing Teeth",
      "Combing Hair",
      "Shaving",
      "Taking Selfie",
      "Texting",
      "Typing",
    ],
  },
  {
    id: "objects",
    name: "Objects",
    icon: "Package",
    color: "text-chart-5",
    words: [
      "Smartphone",
      "Laptop",
      "Television",
      "Remote Control",
      "Headphones",
      "Camera",
      "Microphone",
      "Guitar",
      "Piano",
      "Drums",
      "Trumpet",
      "Violin",
      "Basketball",
      "Football",
      "Soccer Ball",
      "Tennis Racket",
      "Golf Club",
      "Baseball Bat",
      "Bicycle",
      "Skateboard",
      "Scooter",
      "Roller Skates",
      "Snowboard",
      "Skis",
      "Surfboard",
      "Umbrella",
      "Backpack",
      "Suitcase",
      "Wallet",
      "Keys",
      "Watch",
      "Sunglasses",
      "Hat",
      "Shoes",
      "Boots",
      "Gloves",
      "Scarf",
      "Jacket",
      "Book",
      "Notebook",
      "Pen",
      "Pencil",
      "Eraser",
      "Ruler",
      "Scissors",
      "Stapler",
      "Calculator",
      "Coffee Mug",
      "Water Bottle",
      "Plate",
      "Fork",
      "Knife",
      "Spoon",
      "Bowl",
      "Pan",
      "Pot",
      "Toaster",
      "Blender",
      "Microwave",
    ],
  },
];
