import { type Category } from "@shared/schema";

// FREE TRIAL DECK - Unlocked after first game (10+ words guessed)
export const FREE_TRIAL_DECK: Category = {
  id: "tiktok-hits-2025",
  name: "TikTok Hits 2025",
  icon: "Music",
  color: "text-purple-500",
  premium: true,
  freeTrial: true,
  words: [
    "Renegade dance",
    "Skibidi Toilet", 
    "Hawk Tuah", 
    "Very Demure", 
    "Brat Summer Pose", 
    "Ohio Rizz",
    "Savage Love dance",
    "Blinding Lights challenge",
    "WAP dance",
    "Savage remix pose",
    "Say So dance",
    "Toosie Slide",
    "Whip and Nae Nae",
    "Cupid Shuffle",
    "Git Up dance",
    "Level Up challenge",
    "In My Feelings challenge",
    "Old Town Road horse dance",
    "Floss dance",
    "Orange Justice",
    "Default dance Fortnite",
    "Hype dance",
    "Take the L",
    "Best Mate",
    "Hootenanny",
    "Electro Shuffle",
    "Wiggle",
    "Running Man",
    "Shoot dance",
    "Milky Way",
    "Dab",
    "Hit the Quan",
  ],
};

// 35 Premium Category Packs - Each with 25-30 carefully curated words
export const premiumDecks: Category[] = [
  FREE_TRIAL_DECK,
  {
    id: "disney",
    name: "Disney Characters",
    icon: "Sparkles",
    color: "text-pink-500",
    premium: true,
    words: [
      "Mickey Mouse",
      "Minnie Mouse",
      "Donald Duck",
      "Goofy",
      "Pluto",
      "Elsa",
      "Anna",
      "Olaf",
      "Simba",
      "Nala",
      "Timon",
      "Pumbaa",
      "Aladdin",
      "Jasmine",
      "Genie",
      "Ariel",
      "Sebastian",
      "Flounder",
      "Belle",
      "Beast",
      "Cinderella",
      "Snow White",
      "Mulan",
      "Pocahontas",
      "Rapunzel",
      "Moana",
      "Maui",
      "Stitch",
      "Buzz Lightyear",
      "Woody",
    ],
  },
  {
    id: "marvel",
    name: "Marvel Heroes",
    icon: "Zap",
    color: "text-red-500",
    premium: true,
    words: [
      "Iron Man",
      "Captain America",
      "Thor",
      "Hulk",
      "Black Widow",
      "Hawkeye",
      "Spider-Man",
      "Doctor Strange",
      "Black Panther",
      "Scarlet Witch",
      "Vision",
      "Ant-Man",
      "Wasp",
      "Star-Lord",
      "Gamora",
      "Drax",
      "Rocket Raccoon",
      "Groot",
      "Loki",
      "Thanos",
      "Captain Marvel",
      "Winter Soldier",
      "Falcon",
      "War Machine",
      "Nick Fury",
      "Deadpool",
      "Wolverine",
      "Professor X",
      "Magneto",
      "Storm",
    ],
  },
  {
    id: "harry-potter",
    name: "Harry Potter",
    icon: "Wand2",
    color: "text-purple-500",
    premium: true,
    words: [
      "Harry Potter",
      "Hermione Granger",
      "Ron Weasley",
      "Albus Dumbledore",
      "Severus Snape",
      "Voldemort",
      "Draco Malfoy",
      "Hagrid",
      "Dobby",
      "Sirius Black",
      "Remus Lupin",
      "Luna Lovegood",
      "Neville Longbottom",
      "Ginny Weasley",
      "Fred Weasley",
      "George Weasley",
      "Expelliarmus",
      "Patronus",
      "Expecto Patronum",
      "Avada Kedavra",
      "Wingardium Leviosa",
      "Accio",
      "Lumos",
      "Hogwarts",
      "Gryffindor",
      "Slytherin",
      "Hufflepuff",
      "Ravenclaw",
      "Quidditch",
      "Sorting Hat",
    ],
  },
  {
    id: "friends-quotes",
    name: "Friends Quotes",
    icon: "MessageCircle",
    color: "text-orange-500",
    premium: true,
    words: [
      "How You Doin",
      "We Were On A Break",
      "Pivot",
      "Oh My God",
      "Smelly Cat",
      "Unagi",
      "The Rachel",
      "Could I BE Any More",
      "Seven",
      "Moo Point",
      "Princess Consuela Banana Hammock",
      "Crap Bag",
      "He's Her Lobster",
      "Geller Cup",
      "Thanksgiving Pants",
      "Joey Doesn't Share Food",
      "How's It Going",
      "It's Like All My Life",
      "I'm Breezy",
      "Paper Snow A Ghost",
      "Miss Chanandler Bong",
      "Custard Good Jam Good Meat Good",
      "Trifle",
      "Transponster",
      "Regina Phalange",
      "Ken Adams",
      "My Sandwich",
      "Ichiban",
      "Chicken Salad Sandwich",
      "Moist Maker",
    ],
  },
  {
    id: "the-office",
    name: "The Office",
    icon: "Briefcase",
    color: "text-blue-500",
    premium: true,
    words: [
      "That's What She Said",
      "Michael Scott",
      "Dwight Schrute",
      "Jim Halpert",
      "Pam Beesly",
      "Bears Beets Battlestar Galactica",
      "Assistant Regional Manager",
      "Assistant TO THE Regional Manager",
      "Threat Level Midnight",
      "Schrute Farms",
      "Dundies",
      "Pretzel Day",
      "Parkour",
      "Stapler in Jello",
      "Identity Theft Is Not A Joke",
      "Prison Mike",
      "Date Mike",
      "The Nard Dog",
      "Tuna",
      "Big Tuna",
      "Kevin's Chili",
      "Stanley's Crossword",
      "Toby Flenderson",
      "Holly Flax",
      "Ryan The Temp",
      "Fire Guy",
      "Dinner Party",
      "Scott's Tots",
      "Superfan Episodes",
      "Michael Scott Paper Company",
    ],
  },
  {
    id: "tiktok-dances",
    name: "TikTok Dances",
    icon: "Music",
    color: "text-cyan-500",
    premium: true,
    words: [
      "Renegade",
      "Say So Dance",
      "Savage Dance",
      "Blinding Lights Dance",
      "Supalonely Dance",
      "Lottery Dance",
      "Git Up Challenge",
      "Woah Dance",
      "Hit Every Beat",
      "Oh Na Na Na",
      "Cannibal Dance",
      "Throw It Back",
      "Out West Dance",
      "Obsessed Dance",
      "Corvette Corvette",
      "Up Dance",
      "WAP Dance",
      "Mood Dance",
      "34+35 Dance",
      "Levitating Dance",
      "Kiss Me More Dance",
      "Fancy Like",
      "Stay Dance",
      "Industry Baby Dance",
      "Montero Dance",
      "Good 4 U Dance",
      "Butter Dance",
      "Dynamite Dance",
      "Permission to Dance",
      "Anti-Hero Dance",
    ],
  },
  {
    id: "adult-18plus",
    name: "Adult 18+",
    icon: "AlertTriangle",
    color: "text-rose-500",
    premium: true,
    words: [
      "Strip Poker",
      "Body Shots",
      "Truth or Dare",
      "Spin the Bottle",
      "Never Have I Ever",
      "Beer Pong",
      "Flip Cup",
      "King's Cup",
      "Drunk Jenga",
      "Shot Roulette",
      "Tequila Shot",
      "Jager Bomb",
      "Irish Car Bomb",
      "Long Island Iced Tea",
      "Dirty Martini",
      "Sex on the Beach",
      "Screaming Orgasm",
      "Slippery Nipple",
      "Buttery Nipple",
      "Blow Job Shot",
      "Vegas Bomb",
      "Bachelor Party",
      "Bachelorette Party",
      "Bar Crawl",
      "Karaoke Bar",
      "Dive Bar",
      "Wine Tasting",
      "Brewery Tour",
      "Hookah Lounge",
      "After Party",
    ],
  },
  {
    id: "christmas",
    name: "Christmas Songs",
    icon: "Gift",
    color: "text-green-500",
    premium: true,
    words: [
      "Jingle Bells",
      "Silent Night",
      "White Christmas",
      "Rudolph the Red-Nosed Reindeer",
      "Frosty the Snowman",
      "Deck the Halls",
      "Joy to the World",
      "O Holy Night",
      "The First Noel",
      "Hark the Herald Angels Sing",
      "We Wish You a Merry Christmas",
      "Santa Claus Is Coming to Town",
      "Here Comes Santa Claus",
      "Winter Wonderland",
      "Let It Snow",
      "Sleigh Ride",
      "The Christmas Song",
      "I'll Be Home for Christmas",
      "Have Yourself a Merry Little Christmas",
      "It's the Most Wonderful Time of the Year",
      "Rockin' Around the Christmas Tree",
      "Holly Jolly Christmas",
      "Little Drummer Boy",
      "Do You Hear What I Hear",
      "O Come All Ye Faithful",
      "Away in a Manger",
      "All I Want for Christmas Is You",
      "Last Christmas",
      "Feliz Navidad",
      "Wonderful Christmastime",
    ],
  },
  {
    id: "halloween",
    name: "Halloween",
    icon: "Ghost",
    color: "text-orange-600",
    premium: true,
    words: [
      "Vampire",
      "Werewolf",
      "Zombie",
      "Ghost",
      "Witch",
      "Skeleton",
      "Mummy",
      "Frankenstein",
      "Dracula",
      "Headless Horseman",
      "Grim Reaper",
      "Black Cat",
      "Haunted House",
      "Cemetery",
      "Graveyard",
      "Jack-o'-Lantern",
      "Pumpkin Carving",
      "Trick or Treat",
      "Candy Corn",
      "Spider Web",
      "Creepy Crawlies",
      "Full Moon",
      "Scarecrow",
      "Broomstick",
      "Cauldron",
      "Potion",
      "Spellbook",
      "Monster Mash",
      "Thriller Dance",
      "Nightmare Before Christmas",
    ],
  },
  {
    id: "80s-movies",
    name: "80s Movies",
    icon: "Film",
    color: "text-violet-500",
    premium: true,
    words: [
      "E.T.",
      "Back to the Future",
      "The Breakfast Club",
      "Ferris Bueller's Day Off",
      "Ghostbusters",
      "Indiana Jones",
      "Raiders of the Lost Ark",
      "The Goonies",
      "Top Gun",
      "Dirty Dancing",
      "Footloose",
      "Die Hard",
      "The Terminator",
      "Aliens",
      "Blade Runner",
      "The Shining",
      "A Nightmare on Elm Street",
      "Friday the 13th",
      "The Karate Kid",
      "Stand By Me",
      "The Princess Bride",
      "Beetlejuice",
      "Big",
      "Rain Man",
      "When Harry Met Sally",
      "Say Anything",
      "Fast Times at Ridgemont High",
      "Sixteen Candles",
      "Pretty in Pink",
      "Heathers",
    ],
  },
  {
    id: "90s-hits",
    name: "90s Hits",
    icon: "Disc",
    color: "text-lime-500",
    premium: true,
    words: [
      "Smells Like Teen Spirit",
      "Wonderwall",
      "Wannabe",
      "Baby One More Time",
      "No Scrubs",
      "Waterfalls",
      "Creep",
      "Iris",
      "Semi-Charmed Life",
      "Closing Time",
      "MMMBop",
      "Torn",
      "As Long As You Love Me",
      "I Want It That Way",
      "Everybody",
      "Quit Playing Games",
      "Tearin' Up My Heart",
      "Bye Bye Bye",
      "It's Gonna Be Me",
      "No Diggity",
      "Killing Me Softly",
      "Gangsta's Paradise",
      "Jump Around",
      "U Can't Touch This",
      "Ice Ice Baby",
      "Nothing Compares 2 U",
      "Genie in a Bottle",
      "What a Girl Wants",
      "Truly Madly Deeply",
      "I'll Make Love to You",
    ],
  },
  {
    id: "netflix-shows",
    name: "Netflix Shows",
    icon: "Tv",
    color: "text-red-600",
    premium: true,
    words: [
      "Stranger Things",
      "The Crown",
      "Bridgerton",
      "Squid Game",
      "Money Heist",
      "The Witcher",
      "Wednesday",
      "You",
      "Ozark",
      "Breaking Bad",
      "Better Call Saul",
      "Narcos",
      "Black Mirror",
      "The Umbrella Academy",
      "Dark",
      "Lupin",
      "Emily in Paris",
      "Virgin River",
      "Outer Banks",
      "The Queen's Gambit",
      "Cobra Kai",
      "Tiger King",
      "Making a Murderer",
      "The Last Dance",
      "Drive to Survive",
      "Chef's Table",
      "Queer Eye",
      "Selling Sunset",
      "Love Is Blind",
      "Too Hot to Handle",
    ],
  },
  {
    id: "taylor-swift",
    name: "Taylor Swift",
    icon: "Sparkles",
    color: "text-pink-400",
    premium: true,
    words: [
      "Love Story",
      "You Belong With Me",
      "Shake It Off",
      "Blank Space",
      "Bad Blood",
      "Look What You Made Me Do",
      "Delicate",
      "ME!",
      "Lover",
      "Cardigan",
      "Willow",
      "Anti-Hero",
      "Lavender Haze",
      "Karma",
      "Cruel Summer",
      "All Too Well",
      "Red",
      "22",
      "We Are Never Getting Back Together",
      "I Knew You Were Trouble",
      "Style",
      "Wildest Dreams",
      "Out of the Woods",
      "End Game",
      "Getaway Car",
      "Don't Blame Me",
      "The Man",
      "Enchanted",
      "Back to December",
      "Teardrops on My Guitar",
    ],
  },
  {
    id: "billie-eilish",
    name: "Billie Eilish",
    icon: "Music",
    color: "text-emerald-500",
    premium: true,
    words: [
      "Bad Guy",
      "Ocean Eyes",
      "Bellyache",
      "Lovely",
      "When the Party's Over",
      "Bury a Friend",
      "Wish You Were Gay",
      "Xanny",
      "Everything I Wanted",
      "No Time to Die",
      "My Future",
      "Therefore I Am",
      "Happier Than Ever",
      "Lost Cause",
      "Your Power",
      "NDA",
      "Billie Bossa Nova",
      "Goldwing",
      "Halley's Comet",
      "Male Fantasy",
      "Getting Older",
      "I Didn't Change My Number",
      "Overheated",
      "Everybody Dies",
      "My Strange Addiction",
      "You Should See Me in a Crown",
      "All the Good Girls Go to Hell",
      "Ilomilo",
      "Listen Before I Go",
      "I Love You",
    ],
  },
  {
    id: "reality-tv",
    name: "Reality TV Stars",
    icon: "Star",
    color: "text-yellow-500",
    premium: true,
    words: [
      "Kim Kardashian",
      "Kylie Jenner",
      "Khloe Kardashian",
      "Kourtney Kardashian",
      "Kris Jenner",
      "Kendall Jenner",
      "Gordon Ramsay",
      "Simon Cowell",
      "Ryan Seacrest",
      "Jeff Probst",
      "RuPaul",
      "Nicole Richie",
      "Paris Hilton",
      "Snooki",
      "JWoww",
      "The Situation",
      "Pauly D",
      "Teresa Giudice",
      "NeNe Leakes",
      "Bethenny Frankel",
      "Honey Boo Boo",
      "Dog the Bounty Hunter",
      "Bear Grylls",
      "Anthony Bourdain",
      "Guy Fieri",
      "Bobby Flay",
      "Giada De Laurentiis",
      "Chip and Joanna Gaines",
      "The Property Brothers",
      "Marie Kondo",
    ],
  },
  {
    id: "star-wars",
    name: "Star Wars",
    icon: "Rocket",
    color: "text-yellow-400",
    premium: true,
    words: [
      "Luke Skywalker",
      "Princess Leia",
      "Han Solo",
      "Darth Vader",
      "Yoda",
      "Obi-Wan Kenobi",
      "Chewbacca",
      "R2-D2",
      "C-3PO",
      "Anakin Skywalker",
      "Padme Amidala",
      "Qui-Gon Jinn",
      "Mace Windu",
      "Emperor Palpatine",
      "Rey",
      "Finn",
      "Poe Dameron",
      "Kylo Ren",
      "BB-8",
      "The Mandalorian",
      "Baby Yoda",
      "Grogu",
      "Boba Fett",
      "Jango Fett",
      "Ahsoka Tano",
      "Lightsaber",
      "Death Star",
      "Millennium Falcon",
      "The Force",
      "May the Force Be With You",
    ],
  },
  {
    id: "gaming",
    name: "Gaming",
    icon: "Gamepad2",
    color: "text-indigo-500",
    premium: true,
    words: [
      "Mario",
      "Luigi",
      "Sonic the Hedgehog",
      "Pac-Man",
      "Donkey Kong",
      "Pikachu",
      "Link",
      "Zelda",
      "Master Chief",
      "Kratos",
      "Lara Croft",
      "Minecraft Steve",
      "Creeper",
      "Fortnite",
      "Among Us",
      "Roblox",
      "Grand Theft Auto",
      "Call of Duty",
      "League of Legends",
      "Valorant",
      "Overwatch",
      "World of Warcraft",
      "The Sims",
      "Animal Crossing",
      "Pokemon Go",
      "Candy Crush",
      "Angry Birds",
      "Flappy Bird",
      "Temple Run",
      "Subway Surfers",
    ],
  },
  {
    id: "broadway",
    name: "Broadway Musicals",
    icon: "Drama",
    color: "text-amber-500",
    premium: true,
    words: [
      "Hamilton",
      "Wicked",
      "The Lion King",
      "The Phantom of the Opera",
      "Les Miserables",
      "Rent",
      "Chicago",
      "Cats",
      "Grease",
      "Hairspray",
      "Mamma Mia",
      "Jersey Boys",
      "Dear Evan Hansen",
      "Come From Away",
      "Book of Mormon",
      "Avenue Q",
      "Kinky Boots",
      "Waitress",
      "Mean Girls",
      "Frozen",
      "Aladdin",
      "Beauty and the Beast",
      "West Side Story",
      "The Sound of Music",
      "Oklahoma",
      "South Pacific",
      "Fiddler on the Roof",
      "Annie",
      "A Chorus Line",
      "42nd Street",
    ],
  },
  {
    id: "anime",
    name: "Anime",
    icon: "Sparkles",
    color: "text-fuchsia-500",
    premium: true,
    words: [
      "Naruto",
      "Sasuke",
      "Sakura",
      "Kakashi",
      "Goku",
      "Vegeta",
      "Pikachu",
      "Ash Ketchum",
      "Luffy",
      "Zoro",
      "Nami",
      "Ichigo",
      "Light Yagami",
      "L",
      "Edward Elric",
      "Alphonse Elric",
      "Eren Yeager",
      "Mikasa Ackerman",
      "Levi Ackerman",
      "Sailor Moon",
      "Tuxedo Mask",
      "Inuyasha",
      "Kagome",
      "Spike Spiegel",
      "Totoro",
      "Howl",
      "Chihiro",
      "Saitama",
      "All Might",
      "Deku",
    ],
  },
  {
    id: "kpop",
    name: "K-Pop",
    icon: "Music",
    color: "text-rose-400",
    premium: true,
    words: [
      "BTS",
      "Blackpink",
      "Twice",
      "EXO",
      "Red Velvet",
      "NCT",
      "Seventeen",
      "Stray Kids",
      "ITZY",
      "ATEEZ",
      "TXT",
      "Enhypen",
      "Aespa",
      "IVE",
      "NewJeans",
      "LE SSERAFIM",
      "Dynamite",
      "Butter",
      "Ddu-Du Ddu-Du",
      "How You Like That",
      "Kill This Love",
      "Pink Venom",
      "Gangnam Style",
      "Fantastic Baby",
      "Sorry Sorry",
      "Gee",
      "I Am the Best",
      "Cheer Up",
      "TT",
      "Feel Special",
    ],
  },
  {
    id: "memes",
    name: "Memes",
    icon: "Laugh",
    color: "text-cyan-400",
    premium: true,
    words: [
      "Distracted Boyfriend",
      "Woman Yelling at Cat",
      "Success Kid",
      "Disaster Girl",
      "Hide the Pain Harold",
      "Doge",
      "Pepe the Frog",
      "Mocking SpongeBob",
      "Roll Safe",
      "Drake Hotline Bling",
      "Expanding Brain",
      "Galaxy Brain",
      "This Is Fine",
      "Stonks",
      "Not Stonks",
      "Surprised Pikachu",
      "Side Eye Chloe",
      "Arthur Fist",
      "Salt Bae",
      "Yodeling Walmart Kid",
      "Keyboard Cat",
      "Grumpy Cat",
      "Nyan Cat",
      "Bad Luck Brian",
      "Overly Attached Girlfriend",
      "Scumbag Steve",
      "Good Guy Greg",
      "First World Problems",
      "One Does Not Simply",
      "Brace Yourselves",
    ],
  },
  {
    id: "food-chains",
    name: "Food Chains",
    icon: "UtensilsCrossed",
    color: "text-orange-400",
    premium: true,
    words: [
      "McDonald's",
      "Burger King",
      "Wendy's",
      "Taco Bell",
      "KFC",
      "Chick-fil-A",
      "Popeyes",
      "Subway",
      "Chipotle",
      "Panera Bread",
      "Five Guys",
      "In-N-Out Burger",
      "Shake Shack",
      "Sonic",
      "Arby's",
      "Pizza Hut",
      "Domino's",
      "Papa John's",
      "Little Caesars",
      "Olive Garden",
      "Red Lobster",
      "Applebee's",
      "Chili's",
      "TGI Fridays",
      "Buffalo Wild Wings",
      "Dunkin' Donuts",
      "Krispy Kreme",
      "Starbucks",
      "Baskin-Robbins",
      "Dairy Queen",
    ],
  },
  {
    id: "car-brands",
    name: "Car Brands",
    icon: "Car",
    color: "text-slate-600",
    premium: true,
    words: [
      "Tesla",
      "Ferrari",
      "Lamborghini",
      "Porsche",
      "Mercedes-Benz",
      "BMW",
      "Audi",
      "Volkswagen",
      "Toyota",
      "Honda",
      "Ford",
      "Chevrolet",
      "Dodge",
      "Jeep",
      "Ram",
      "Nissan",
      "Mazda",
      "Subaru",
      "Hyundai",
      "Kia",
      "Lexus",
      "Acura",
      "Infiniti",
      "Cadillac",
      "Lincoln",
      "Buick",
      "GMC",
      "Chrysler",
      "Jaguar",
      "Land Rover",
    ],
  },
  {
    id: "countries",
    name: "Countries",
    icon: "Globe",
    color: "text-blue-600",
    premium: true,
    words: [
      "United States",
      "Canada",
      "Mexico",
      "Brazil",
      "Argentina",
      "United Kingdom",
      "France",
      "Germany",
      "Italy",
      "Spain",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Switzerland",
      "Austria",
      "Sweden",
      "Norway",
      "Denmark",
      "Finland",
      "Russia",
      "Poland",
      "Greece",
      "Turkey",
      "Egypt",
      "South Africa",
      "China",
      "Japan",
      "South Korea",
      "India",
      "Australia",
    ],
  },
  {
    id: "dc-heroes",
    name: "DC Superheroes",
    icon: "Shield",
    color: "text-blue-700",
    premium: true,
    words: [
      "Superman",
      "Batman",
      "Wonder Woman",
      "The Flash",
      "Aquaman",
      "Green Lantern",
      "Cyborg",
      "Shazam",
      "Robin",
      "Nightwing",
      "Batgirl",
      "Catwoman",
      "Harley Quinn",
      "Joker",
      "Lex Luthor",
      "Darkseid",
      "Doomsday",
      "Brainiac",
      "Poison Ivy",
      "Penguin",
      "Riddler",
      "Two-Face",
      "Bane",
      "Scarecrow",
      "Green Arrow",
      "Black Canary",
      "Supergirl",
      "Martian Manhunter",
      "Hawkman",
      "Hawkgirl",
    ],
  },
  {
    id: "cartoons",
    name: "Cartoon Characters",
    icon: "Smile",
    color: "text-teal-500",
    premium: true,
    words: [
      "SpongeBob SquarePants",
      "Patrick Star",
      "Squidward",
      "Mr. Krabs",
      "Sandy Cheeks",
      "Bugs Bunny",
      "Daffy Duck",
      "Tom and Jerry",
      "Scooby-Doo",
      "Shaggy",
      "Fred Flintstone",
      "Barney Rubble",
      "Homer Simpson",
      "Bart Simpson",
      "Peter Griffin",
      "Stewie Griffin",
      "Eric Cartman",
      "Kenny McCormick",
      "Stan Marsh",
      "Kyle Broflovski",
      "Bender",
      "Fry",
      "Rick Sanchez",
      "Morty Smith",
      "Courage the Cowardly Dog",
      "Dexter",
      "Johnny Bravo",
      "Powerpuff Girls",
      "Teen Titans",
      "Avatar Aang",
    ],
  },
  {
    id: "zodiac",
    name: "Zodiac Signs",
    icon: "Star",
    color: "text-purple-400",
    premium: true,
    words: [
      "Aries",
      "Taurus",
      "Gemini",
      "Cancer",
      "Leo",
      "Virgo",
      "Libra",
      "Scorpio",
      "Sagittarius",
      "Capricorn",
      "Aquarius",
      "Pisces",
      "Fire Sign",
      "Earth Sign",
      "Air Sign",
      "Water Sign",
      "Rising Sign",
      "Moon Sign",
      "Sun Sign",
      "Mercury Retrograde",
      "Venus in Retrograde",
      "Birth Chart",
      "Horoscope",
      "Astrology",
      "Constellation",
      "Star Sign",
      "Compatible Signs",
      "Cusp",
      "Houses",
      "Planets",
    ],
  },
  {
    id: "board-games",
    name: "Board Games",
    icon: "Puzzle",
    color: "text-brown-500",
    premium: true,
    words: [
      "Monopoly",
      "Scrabble",
      "Chess",
      "Checkers",
      "Clue",
      "Risk",
      "Battleship",
      "Sorry",
      "Candy Land",
      "Chutes and Ladders",
      "The Game of Life",
      "Trouble",
      "Operation",
      "Connect Four",
      "Jenga",
      "Uno",
      "Phase 10",
      "Skip-Bo",
      "Yahtzee",
      "Boggle",
      "Pictionary",
      "Trivial Pursuit",
      "Apples to Apples",
      "Cards Against Humanity",
      "Settlers of Catan",
      "Ticket to Ride",
      "Pandemic",
      "Codenames",
      "Exploding Kittens",
      "Secret Hitler",
    ],
  },
  {
    id: "tech-brands",
    name: "Tech Brands",
    icon: "Laptop",
    color: "text-gray-600",
    premium: true,
    words: [
      "Apple",
      "Microsoft",
      "Google",
      "Amazon",
      "Facebook",
      "Meta",
      "Instagram",
      "Twitter",
      "X",
      "TikTok",
      "Snapchat",
      "YouTube",
      "Netflix",
      "Spotify",
      "Samsung",
      "Sony",
      "Nintendo",
      "PlayStation",
      "Xbox",
      "Dell",
      "HP",
      "Lenovo",
      "Asus",
      "Acer",
      "Intel",
      "AMD",
      "Nvidia",
      "Adobe",
      "Zoom",
      "Slack",
    ],
  },
  {
    id: "fashion-brands",
    name: "Fashion Brands",
    icon: "Shirt",
    color: "text-pink-600",
    premium: true,
    words: [
      "Gucci",
      "Louis Vuitton",
      "Chanel",
      "Prada",
      "Versace",
      "Dolce & Gabbana",
      "Armani",
      "Burberry",
      "Dior",
      "Fendi",
      "Givenchy",
      "Valentino",
      "Balenciaga",
      "Saint Laurent",
      "Hermes",
      "Cartier",
      "Tiffany & Co",
      "Rolex",
      "Nike",
      "Adidas",
      "Puma",
      "Under Armour",
      "Lululemon",
      "Zara",
      "H&M",
      "Forever 21",
      "Gap",
      "Old Navy",
      "American Eagle",
      "Abercrombie & Fitch",
    ],
  },
  {
    id: "emojis",
    name: "Emojis",
    icon: "Smile",
    color: "text-yellow-400",
    premium: true,
    words: [
      "Crying Laughing Face",
      "Heart Eyes",
      "Thinking Face",
      "Face with Tears of Joy",
      "Skull",
      "Fire",
      "Hundred Points",
      "Clapping Hands",
      "Thumbs Up",
      "Thumbs Down",
      "Praying Hands",
      "Folded Hands",
      "Red Heart",
      "Broken Heart",
      "Sparkling Heart",
      "Purple Heart",
      "Blue Heart",
      "Green Heart",
      "Yellow Heart",
      "Orange Heart",
      "Peace Sign",
      "OK Hand",
      "Fist Bump",
      "Raised Fist",
      "Victory Hand",
      "Rock On",
      "Call Me Hand",
      "Flexed Bicep",
      "Middle Finger",
      "Waving Hand",
    ],
  },
  {
    id: "dad-jokes",
    name: "Dad Jokes",
    icon: "Laugh",
    color: "text-brown-600",
    premium: true,
    words: [
      "I'm Hungry Hi Hungry I'm Dad",
      "Why Did the Chicken Cross the Road",
      "Knock Knock Who's There",
      "Orange You Glad",
      "Don't Cry Over Spilled Milk",
      "The Dad Bod",
      "Lawn Mower",
      "Grill Master",
      "Thermostat Wars",
      "Cargo Shorts",
      "New Balance Shoes",
      "White Sneakers",
      "Baseball Cap",
      "Fanny Pack",
      "Reading the Newspaper",
      "Falling Asleep on the Couch",
      "Snoring Loudly",
      "Bad Puns",
      "Corny Jokes",
      "Eye Rolling",
      "Embarrassing Your Kids",
      "Asking Are We There Yet",
      "Turning Off All the Lights",
      "Adjusting the Thermostat",
      "Mowing in Patterns",
      "Washing the Car",
      "Grilling in All Weather",
      "Wearing Socks with Sandals",
      "Taking Forever at Home Depot",
      "Falling Asleep During Movies",
    ],
  },
  {
    id: "pickup-lines",
    name: "Pickup Lines",
    icon: "Heart",
    color: "text-red-400",
    premium: true,
    words: [
      "Are You a Magician",
      "Do You Believe in Love at First Sight",
      "Is Your Name Google",
      "Are You a Parking Ticket",
      "Do You Have a Map",
      "Are You a Camera",
      "If You Were a Vegetable",
      "Are You Made of Copper and Tellurium",
      "Do You Have a Band-Aid",
      "Are You Australian",
      "Is Your Dad a Boxer",
      "Are You a Loan",
      "Did It Hurt When You Fell from Heaven",
      "Can I Follow You Home",
      "Are You a Time Traveler",
      "Is There an Airport Nearby",
      "Are You Wi-Fi",
      "Do You Like Raisins",
      "Are You a Campfire",
      "Is Your Name Ariel",
      "Are You French",
      "Do You Play Soccer",
      "Are You a Beaver",
      "Is Your Body from McDonald's",
      "Are You a Volcano",
      "Do You Have a Sunburn",
      "Are You a Keyboard",
      "Is Your Name Chapstick",
      "Are You a Magnet",
      "Do You Believe in Fate",
    ],
  },
  {
    id: "wedding",
    name: "Wedding Things",
    icon: "Heart",
    color: "text-rose-300",
    premium: true,
    words: [
      "Bride",
      "Groom",
      "Bridesmaid",
      "Groomsman",
      "Maid of Honor",
      "Best Man",
      "Flower Girl",
      "Ring Bearer",
      "Wedding Dress",
      "Tuxedo",
      "Veil",
      "Bouquet",
      "Boutonniere",
      "Wedding Cake",
      "Champagne Toast",
      "First Dance",
      "Father-Daughter Dance",
      "Mother-Son Dance",
      "Wedding Vows",
      "Exchange of Rings",
      "I Do",
      "You May Kiss the Bride",
      "Walking Down the Aisle",
      "Throwing the Bouquet",
      "Throwing the Garter",
      "Wedding Reception",
      "Honeymoon",
      "Save the Date",
      "Wedding Invitation",
      "RSVP",
    ],
  },
];
